import React, { createContext, useContext, useState, ReactNode } from "react";

export type LanguageCode = "en" | "hi" | "te" | "ta" | "kn" | "mr";

interface Language {
  code: LanguageCode;
  name: string;
  flag: string;
}

export const languages: Language[] = [
  { code: "en", name: "English", flag: "🇬🇧" },
  { code: "hi", name: "हिंदी", flag: "🇮🇳" },
  { code: "te", name: "తెలుగు", flag: "🇮🇳" },
  { code: "ta", name: "தமிழ்", flag: "🇮🇳" },
  { code: "kn", name: "ಕನ್ನಡ", flag: "🇮🇳" },
  { code: "mr", name: "मराठी", flag: "🇮🇳" },
];

// Translations for the entire app
export const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Landing
    smartFarming: "Smart Farming Technology",
    heroTitle: "Smart Crop Advisor",
    heroTitleSub: "System",
    heroDescription: "AI & IoT Powered Crop Recommendation for Smart Farming. Make data-driven decisions with real-time soil analysis and weather insights.",
    getRecommendation: "Get Recommendation",
    viewDashboard: "View Dashboard",
    features: "Features",
    howItWorks: "How it Works",
    keyFeatures: "Key Features",
    keyFeaturesDesc: "Everything you need to optimize your farming with smart technology",
    aiCropRecommendation: "AI Crop Recommendation",
    aiCropRecommendationDesc: "Get smart suggestions for the best crops based on your soil and weather conditions",
    realTimeWeather: "Real-time Weather Insights",
    realTimeWeatherDesc: "Access current and forecasted weather data to plan your farming activities",
    smartAlerts: "Smart Alerts",
    smartAlertsDesc: "Receive early warnings about weather risks, irrigation needs, and crop health",
    multilingualChatbot: "Multilingual Chatbot",
    multilingualChatbotDesc: "Ask questions in your language and get farming advice instantly",
    howItWorksTitle: "How It Works",
    howItWorksDesc: "From soil sensors to smart recommendations in 4 simple steps",
    soilAnalysis: "Soil Analysis",
    soilAnalysisDesc: "IoT sensors measure NPK, moisture, pH, and temperature",
    weatherData: "Weather Data",
    weatherDataDesc: "Real-time weather and forecast integration",
    aiProcessing: "AI Processing",
    aiProcessingDesc: "Machine learning analyzes your farm conditions",
    recommendation: "Recommendation",
    recommendationDesc: "Get personalized crop and farming advice",
    iotIntegration: "IoT Sensor Integration",
    iotIntegrationDesc: "Real-time monitoring with professional-grade sensors",
    npkSensor: "NPK Sensor",
    npkSensorDesc: "Nitrogen, Phosphorus, Potassium levels",
    moistureSensor: "Moisture Sensor",
    moistureSensorDesc: "Soil moisture percentage",
    dhtSensor: "DHT11/22",
    dhtSensorDesc: "Temperature & humidity",
    phSensor: "pH Sensor",
    phSensorDesc: "Soil acidity measurement",
    readyToOptimize: "Ready to Optimize Your Farm?",
    readyToOptimizeDesc: "Get started with smart farming today and increase your crop yield with AI-powered recommendations.",
    getStartedNow: "Get Started Now",
    talkToAI: "Talk to AI Assistant",
    // Dashboard & Common
    dashboard: "Dashboard",
    history: "History",
    alerts: "Alerts",
    recommendations: "Recommendations",
    chatbot: "Chatbot",
    selectLanguage: "Select Language",
    // Alerts page
    alertsWarnings: "Alerts & Warnings",
    stayInformed: "Stay informed about risks and take timely action",
    markAllRead: "Mark all as read",
    totalAlerts: "Total Alerts",
    unread: "Unread",
    highPriority: "High Priority",
    resolved: "Resolved",
    allAlerts: "All Alerts",
    suggestedAction: "Suggested Action",
    allClear: "All Clear!",
    noActiveAlerts: "No active alerts at the moment",
    noUnreadAlerts: "No unread alerts",
    noHighPriorityAlerts: "No high priority alerts",
    // Recommendations
    aiCropRecommendations: "AI Crop Recommendations",
    getPersonalizedAdvice: "Get personalized crop advice based on your soil and conditions",
    currentSensorReadings: "Current Sensor Readings",
    selectSoilType: "Select Your Soil Type",
    getAIRecommendations: "Get AI Recommendations",
    top4Crops: "Top 4 Recommended Crops",
    askAIDetails: "Ask AI for More Details",
    expectedYield: "Expected Yield",
    waterNeeds: "Water Needs",
    bestSowing: "Best Sowing",
    harvestTime: "Harvest Time",
    fertilizerTip: "Fertilizer Tip",
    selectThisCrop: "Select This Crop",
    needMoreHelp: "Need More Help?",
    needMoreHelpDesc: "Our AI assistant can provide detailed guidance on farming practices, answer your questions in multiple languages, and help you make the best decisions.",
    cropSelected: "Crop Selected",
    manageYourCrop: "Manage your crop with personalized recommendations",
    changeCrop: "Change Crop",
    // Soil Types
    blackSoil: "Black Soil",
    blackSoilDesc: "Rich in calcium, magnesium, iron",
    redSoil: "Red Soil",
    redSoilDesc: "Rich in iron, good for dry farming",
    claySoil: "Clay Soil",
    claySoilDesc: "Heavy, retains water",
    sandySoil: "Sandy Soil",
    sandySoilDesc: "Light, drains quickly",
    loamySoil: "Loamy Soil",
    loamySoilDesc: "Balanced, ideal for most crops",
    alluvialSoil: "Alluvial Soil",
    alluvialSoilDesc: "Fertile, near river deposits",
    lateriteSoil: "Laterite Soil",
    lateriteSoilDesc: "Acidic, rich in iron and aluminum",
    // History
    weatherSensorHistory: "Weather & Sensor History",
    understandTrends: "Understand past weather and sensor data trends",
    weather: "Weather",
    sensors: "Sensors",
    weekly: "Weekly",
    monthly: "Monthly",
    seasonal: "Seasonal",
    // Chatbot
    cropAdvisorAI: "Crop Advisor AI",
    onlineMultilingual: "Online • Multilingual Support",
    quickQuestions: "Quick questions",
    askAnything: "Ask me anything about your crops...",
    uploadImage: "Upload an image to analyze crop condition",
    // Selected crop specific
    selectedCropAlerts: "Alerts for",
    wateringSchedule: "Watering Schedule",
    fertilizerSchedule: "Fertilizer Schedule",
    pestAlert: "Pest Alert",
    growthStage: "Growth Stage",
  },
  hi: {
    smartFarming: "स्मार्ट खेती तकनीक",
    heroTitle: "स्मार्ट फसल सलाहकार",
    heroTitleSub: "प्रणाली",
    heroDescription: "स्मार्ट खेती के लिए AI और IoT संचालित फसल सिफारिश। वास्तविक समय मिट्टी विश्लेषण और मौसम अंतर्दृष्टि के साथ डेटा-संचालित निर्णय लें।",
    getRecommendation: "सिफारिश प्राप्त करें",
    viewDashboard: "डैशबोर्ड देखें",
    features: "विशेषताएं",
    howItWorks: "यह कैसे काम करता है",
    keyFeatures: "मुख्य विशेषताएं",
    keyFeaturesDesc: "स्मार्ट तकनीक के साथ अपनी खेती को अनुकूलित करने के लिए सब कुछ",
    aiCropRecommendation: "AI फसल सिफारिश",
    aiCropRecommendationDesc: "अपनी मिट्टी और मौसम की स्थिति के आधार पर सर्वोत्तम फसलों के लिए स्मार्ट सुझाव प्राप्त करें",
    realTimeWeather: "वास्तविक समय मौसम अंतर्दृष्टि",
    realTimeWeatherDesc: "अपनी खेती गतिविधियों की योजना बनाने के लिए वर्तमान और पूर्वानुमानित मौसम डेटा प्राप्त करें",
    smartAlerts: "स्मार्ट अलर्ट",
    smartAlertsDesc: "मौसम जोखिम, सिंचाई जरूरतों और फसल स्वास्थ्य के बारे में प्रारंभिक चेतावनी प्राप्त करें",
    multilingualChatbot: "बहुभाषी चैटबॉट",
    multilingualChatbotDesc: "अपनी भाषा में प्रश्न पूछें और तुरंत खेती सलाह प्राप्त करें",
    howItWorksTitle: "यह कैसे काम करता है",
    howItWorksDesc: "मिट्टी सेंसर से स्मार्ट सिफारिशों तक 4 सरल चरणों में",
    soilAnalysis: "मिट्टी विश्लेषण",
    soilAnalysisDesc: "IoT सेंसर NPK, नमी, pH और तापमान मापते हैं",
    weatherData: "मौसम डेटा",
    weatherDataDesc: "वास्तविक समय मौसम और पूर्वानुमान एकीकरण",
    aiProcessing: "AI प्रसंस्करण",
    aiProcessingDesc: "मशीन लर्निंग आपकी खेत की स्थिति का विश्लेषण करती है",
    recommendation: "सिफारिश",
    recommendationDesc: "व्यक्तिगत फसल और खेती सलाह प्राप्त करें",
    iotIntegration: "IoT सेंसर एकीकरण",
    iotIntegrationDesc: "पेशेवर-ग्रेड सेंसर के साथ वास्तविक समय निगरानी",
    npkSensor: "NPK सेंसर",
    npkSensorDesc: "नाइट्रोजन, फॉस्फोरस, पोटैशियम स्तर",
    moistureSensor: "नमी सेंसर",
    moistureSensorDesc: "मिट्टी नमी प्रतिशत",
    dhtSensor: "DHT11/22",
    dhtSensorDesc: "तापमान और आर्द्रता",
    phSensor: "pH सेंसर",
    phSensorDesc: "मिट्टी अम्लता माप",
    readyToOptimize: "अपने खेत को अनुकूलित करने के लिए तैयार?",
    readyToOptimizeDesc: "आज स्मार्ट खेती शुरू करें और AI-संचालित सिफारिशों के साथ अपनी फसल उपज बढ़ाएं।",
    getStartedNow: "अभी शुरू करें",
    talkToAI: "AI सहायक से बात करें",
    dashboard: "डैशबोर्ड",
    history: "इतिहास",
    alerts: "अलर्ट",
    recommendations: "सिफारिशें",
    chatbot: "चैटबॉट",
    selectLanguage: "भाषा चुनें",
    alertsWarnings: "अलर्ट और चेतावनियां",
    stayInformed: "जोखिमों के बारे में सूचित रहें और समय पर कार्रवाई करें",
    markAllRead: "सभी को पढ़ा हुआ चिह्नित करें",
    totalAlerts: "कुल अलर्ट",
    unread: "अपठित",
    highPriority: "उच्च प्राथमिकता",
    resolved: "हल किया गया",
    allAlerts: "सभी अलर्ट",
    suggestedAction: "सुझाई गई कार्रवाई",
    allClear: "सब ठीक है!",
    noActiveAlerts: "इस समय कोई सक्रिय अलर्ट नहीं",
    noUnreadAlerts: "कोई अपठित अलर्ट नहीं",
    noHighPriorityAlerts: "कोई उच्च प्राथमिकता अलर्ट नहीं",
    aiCropRecommendations: "AI फसल सिफारिशें",
    getPersonalizedAdvice: "अपनी मिट्टी और स्थितियों के आधार पर व्यक्तिगत फसल सलाह प्राप्त करें",
    currentSensorReadings: "वर्तमान सेंसर रीडिंग",
    selectSoilType: "अपनी मिट्टी का प्रकार चुनें",
    getAIRecommendations: "AI सिफारिशें प्राप्त करें",
    top4Crops: "शीर्ष 4 अनुशंसित फसलें",
    askAIDetails: "AI से अधिक विवरण पूछें",
    expectedYield: "अपेक्षित उपज",
    waterNeeds: "पानी की जरूरत",
    bestSowing: "सर्वोत्तम बुवाई",
    harvestTime: "कटाई का समय",
    fertilizerTip: "उर्वरक सुझाव",
    selectThisCrop: "इस फसल को चुनें",
    needMoreHelp: "अधिक सहायता चाहिए?",
    needMoreHelpDesc: "हमारा AI सहायक खेती प्रथाओं पर विस्तृत मार्गदर्शन प्रदान कर सकता है।",
    cropSelected: "फसल चयनित",
    manageYourCrop: "व्यक्तिगत सिफारिशों के साथ अपनी फसल प्रबंधित करें",
    changeCrop: "फसल बदलें",
    blackSoil: "काली मिट्टी",
    blackSoilDesc: "कैल्शियम, मैग्नीशियम, आयरन से भरपूर",
    redSoil: "लाल मिट्टी",
    redSoilDesc: "आयरन से भरपूर, सूखी खेती के लिए अच्छी",
    claySoil: "चिकनी मिट्टी",
    claySoilDesc: "भारी, पानी बनाए रखती है",
    sandySoil: "रेतीली मिट्टी",
    sandySoilDesc: "हल्की, जल्दी निकास",
    loamySoil: "दोमट मिट्टी",
    loamySoilDesc: "संतुलित, अधिकांश फसलों के लिए आदर्श",
    alluvialSoil: "जलोढ़ मिट्टी",
    alluvialSoilDesc: "उपजाऊ, नदी जमा के पास",
    lateriteSoil: "लेटराइट मिट्टी",
    lateriteSoilDesc: "अम्लीय, आयरन और एल्युमीनियम से भरपूर",
    weatherSensorHistory: "मौसम और सेंसर इतिहास",
    understandTrends: "पिछले मौसम और सेंसर डेटा रुझानों को समझें",
    weather: "मौसम",
    sensors: "सेंसर",
    weekly: "साप्ताहिक",
    monthly: "मासिक",
    seasonal: "मौसमी",
    cropAdvisorAI: "फसल सलाहकार AI",
    onlineMultilingual: "ऑनलाइन • बहुभाषी समर्थन",
    quickQuestions: "त्वरित प्रश्न",
    askAnything: "अपनी फसलों के बारे में कुछ भी पूछें...",
    uploadImage: "फसल की स्थिति का विश्लेषण करने के लिए छवि अपलोड करें",
    selectedCropAlerts: "के लिए अलर्ट",
    wateringSchedule: "सिंचाई अनुसूची",
    fertilizerSchedule: "उर्वरक अनुसूची",
    pestAlert: "कीट अलर्ट",
    growthStage: "विकास चरण",
  },
  te: {
    smartFarming: "స్మార్ట్ వ్యవసాయ టెక్నాలజీ",
    heroTitle: "స్మార్ట్ పంట సలహాదారు",
    heroTitleSub: "వ్యవస్థ",
    heroDescription: "స్మార్ట్ వ్యవసాయం కోసం AI & IoT ఆధారిత పంట సిఫార్సు. రియల్-టైమ్ నేల విశ్లేషణ మరియు వాతావరణ అంతర్దృష్టులతో డేటా-ఆధారిత నిర్ణయాలు తీసుకోండి.",
    getRecommendation: "సిఫార్సు పొందండి",
    viewDashboard: "డాష్‌బోర్డ్ చూడండి",
    features: "ఫీచర్లు",
    howItWorks: "ఇది ఎలా పని చేస్తుంది",
    keyFeatures: "ముఖ్య ఫీచర్లు",
    keyFeaturesDesc: "స్మార్ట్ టెక్నాలజీతో మీ వ్యవసాయాన్ని ఆప్టిమైజ్ చేయడానికి అవసరమైనవన్నీ",
    aiCropRecommendation: "AI పంట సిఫార్సు",
    aiCropRecommendationDesc: "మీ నేల మరియు వాతావరణ పరిస్థితుల ఆధారంగా ఉత్తమ పంటలకు స్మార్ట్ సూచనలు పొందండి",
    dashboard: "డాష్‌బోర్డ్",
    history: "చరిత్ర",
    alerts: "హెచ్చరికలు",
    recommendations: "సిఫార్సులు",
    chatbot: "చాట్‌బాట్",
    selectLanguage: "భాష ఎంచుకోండి",
    selectSoilType: "మీ నేల రకం ఎంచుకోండి",
    getAIRecommendations: "AI సిఫార్సులు పొందండి",
    blackSoil: "నల్ల నేల",
    blackSoilDesc: "కాల్షియం, మెగ్నీషియం, ఐరన్ తో సమృద్ధి",
    redSoil: "ఎర్ర నేల",
    redSoilDesc: "ఐరన్ తో సమృద్ధి, పొడి వ్యవసాయానికి మంచిది",
    claySoil: "బంకమట్టి",
    claySoilDesc: "భారీ, నీరు నిలుపుతుంది",
    sandySoil: "ఇసుక నేల",
    sandySoilDesc: "తేలిక, త్వరగా డ్రెయిన్ అవుతుంది",
    loamySoil: "లోమి నేల",
    loamySoilDesc: "సమతుల్య, చాలా పంటలకు ఆదర్శం",
    alluvialSoil: "ఒండ్రు నేల",
    alluvialSoilDesc: "సారవంతమైన, నది నిక్షేపాల సమీపంలో",
    lateriteSoil: "లేటరైట్ నేల",
    lateriteSoilDesc: "ఆమ్ల, ఐరన్ మరియు అల్యూమినియంతో సమృద్ధి",
    selectThisCrop: "ఈ పంటను ఎంచుకోండి",
  },
  ta: {
    smartFarming: "ஸ்மார்ட் விவசாய தொழில்நுட்பம்",
    heroTitle: "ஸ்மார்ட் பயிர் ஆலோசகர்",
    heroTitleSub: "அமைப்பு",
    heroDescription: "ஸ்மார்ட் விவசாயத்திற்கான AI & IoT இயக்கும் பயிர் பரிந்துரை.",
    getRecommendation: "பரிந்துரை பெறுங்கள்",
    viewDashboard: "டாஷ்போர்டைப் பார்க்கவும்",
    features: "அம்சங்கள்",
    howItWorks: "இது எவ்வாறு செயல்படுகிறது",
    dashboard: "டாஷ்போர்ட்",
    history: "வரலாறு",
    alerts: "எச்சரிக்கைகள்",
    recommendations: "பரிந்துரைகள்",
    chatbot: "சாட்போட்",
    selectLanguage: "மொழியைத் தேர்ந்தெடுக்கவும்",
    selectSoilType: "உங்கள் மண் வகையைத் தேர்ந்தெடுக்கவும்",
    getAIRecommendations: "AI பரிந்துரைகளைப் பெறுங்கள்",
    blackSoil: "கருப்பு மண்",
    blackSoilDesc: "கால்சியம், மெக்னீசியம், இரும்பு நிறைந்தது",
    redSoil: "சிவப்பு மண்",
    redSoilDesc: "இரும்பு நிறைந்தது, வறண்ட விவசாயத்திற்கு நல்லது",
    claySoil: "களிமண்",
    claySoilDesc: "கனமான, தண்ணீரைத் தக்கவைக்கும்",
    sandySoil: "மணல் மண்",
    sandySoilDesc: "இலகுவான, விரைவாக வடிகால்",
    loamySoil: "களிமண்",
    loamySoilDesc: "சமநிலையான, பெரும்பாலான பயிர்களுக்கு ஏற்றது",
    alluvialSoil: "வண்டல் மண்",
    alluvialSoilDesc: "வளமான, நதி படிவுகள் அருகில்",
    lateriteSoil: "லேட்ரைட் மண்",
    lateriteSoilDesc: "அமில, இரும்பு மற்றும் அலுமினியம் நிறைந்தது",
    selectThisCrop: "இந்த பயிரைத் தேர்ந்தெடுக்கவும்",
  },
  kn: {
    smartFarming: "ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ತಂತ್ರಜ್ಞಾನ",
    heroTitle: "ಸ್ಮಾರ್ಟ್ ಬೆಳೆ ಸಲಹೆಗಾರ",
    heroTitleSub: "ವ್ಯವಸ್ಥೆ",
    heroDescription: "ಸ್ಮಾರ್ಟ್ ಕೃಷಿಗಾಗಿ AI & IoT ಚಾಲಿತ ಬೆಳೆ ಶಿಫಾರಸು.",
    getRecommendation: "ಶಿಫಾರಸು ಪಡೆಯಿರಿ",
    viewDashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ವೀಕ್ಷಿಸಿ",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    history: "ಇತಿಹಾಸ",
    alerts: "ಎಚ್ಚರಿಕೆಗಳು",
    recommendations: "ಶಿಫಾರಸುಗಳು",
    chatbot: "ಚಾಟ್‌ಬಾಟ್",
    selectLanguage: "ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ",
    selectSoilType: "ನಿಮ್ಮ ಮಣ್ಣಿನ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    blackSoil: "ಕಪ್ಪು ಮಣ್ಣು",
    blackSoilDesc: "ಕ್ಯಾಲ್ಸಿಯಂ, ಮೆಗ್ನೀಸಿಯಂ, ಕಬ್ಬಿಣದಿಂದ ಸಮೃದ್ಧ",
    redSoil: "ಕೆಂಪು ಮಣ್ಣು",
    redSoilDesc: "ಕಬ್ಬಿಣದಿಂದ ಸಮೃದ್ಧ, ಒಣ ಕೃಷಿಗೆ ಒಳ್ಳೆಯದು",
    selectThisCrop: "ಈ ಬೆಳೆ ಆಯ್ಕೆಮಾಡಿ",
  },
  mr: {
    smartFarming: "स्मार्ट शेती तंत्रज्ञान",
    heroTitle: "स्मार्ट पीक सल्लागार",
    heroTitleSub: "प्रणाली",
    heroDescription: "स्मार्ट शेतीसाठी AI आणि IoT चालित पीक शिफारस.",
    getRecommendation: "शिफारस मिळवा",
    viewDashboard: "डॅशबोर्ड पहा",
    dashboard: "डॅशबोर्ड",
    history: "इतिहास",
    alerts: "सूचना",
    recommendations: "शिफारसी",
    chatbot: "चॅटबॉट",
    selectLanguage: "भाषा निवडा",
    selectSoilType: "तुमचा माती प्रकार निवडा",
    blackSoil: "काळी माती",
    blackSoilDesc: "कॅल्शियम, मॅग्नेशियम, लोहाने समृद्ध",
    redSoil: "लाल माती",
    redSoilDesc: "लोहाने समृद्ध, कोरड्या शेतीसाठी चांगली",
    selectThisCrop: "हे पीक निवडा",
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem("crop-advisor-language");
    return (saved as LanguageCode) || "en";
  });

  const handleSetLanguage = (lang: LanguageCode) => {
    setLanguage(lang);
    localStorage.setItem("crop-advisor-language", lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
